### ISSUE TITLE
Renaming files

### ISSUE THREAD

**Issue by jonatan5524** [TheAlgorithms/Go#548] opened 2022-10-01 19:46 UTC
**Describe the bug**
There are some algorithms, I saw specific in searches but maybe there are more, like Binary search where The file name in the repository is binary, but in all other languages are binarySearch or something like that. 
That causes the website not to present the Go language option on the Binary Search page.

**To Reproduce**
1. Go to https://the-algorithms.com/category/searches
2. Click on BinarySearch (there is not a Go option there in languages)
3. Back to https://the-algorithms.com/category/searches
4. There is only in Golang a Binary page

**Expected behavior**
One page of BinaryPage with Golang options as the other languages 

**Screenshots**
![image](https://user-images.githubusercontent.com/37303618/193425774-62b94371-7ca4-4c1b-b25c-5aad925eaa93.png)
![image](https://user-images.githubusercontent.com/37303618/193425785-7c813016-bf8e-4607-a4c4-e726d55d732e.png)

**Additional context**
As I mentioned at first, there are maybe more files like this.

**Comment by tjgurwara99** [comment] 2022-10-02 16:42
This is not the issue for this repository to fix. It's an issue that cannot be fixed if we want to keep to Go idioms since the idioms are in direct conflict with the naming conventions in other language.

**Comment by raklaptudirm** [comment] 2022-10-03 13:43
We are trying to update the website code to fix this issue. Closing since the issue is not with this repo.

**Closed by raklaptudirm** 2022-10-03 13:43 UTC
Labels: bug
